import { Link } from 'react-router-dom'
import { 
  ChartBarIcon, 
  CpuChipIcon, 
  ClockIcon, 
  TrophyIcon 
} from '@heroicons/react/24/outline'
import { Button } from '../components/ui'

export function HomePage() {
  const features = [
    {
      icon: ChartBarIcon,
      title: 'Game Analysis',
      description: 'Upload PGN files and get detailed analysis of your opponents\' games using Stockfish engine.'
    },
    {
      icon: CpuChipIcon,
      title: 'AI-Powered Insights',
      description: 'Get personalized preparation plans generated by advanced AI to exploit your opponents\' weaknesses.'
    },
    {
      icon: ClockIcon,
      title: 'Daily Training',
      description: 'Receive customized daily drills and tactics to improve your tournament preparation.'
    },
    {
      icon: TrophyIcon,
      title: 'Tournament Ready',
      description: 'Build comprehensive prep plans with opening traps, tactical patterns, and time management tips.'
    }
  ]

  return (
    <div className="min-h-screen">
      {/* Header */}
      <header className="bg-white border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center py-6">
            <div className="flex items-center">
              <div className="h-10 w-10 bg-chess-primary rounded-lg flex items-center justify-center">
                <span className="text-white font-bold text-xl">♕</span>
              </div>
              <span className="ml-3 text-xl font-bold text-gray-900">
                AI Chess Tournament Prep Agent
              </span>
            </div>
            <div className="flex space-x-4">
              <Link to="/login">
                <Button variant="ghost">Sign In</Button>
              </Link>
              <Link to="/register">
                <Button>Get Started</Button>
              </Link>
            </div>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="bg-gradient-to-r from-chess-primary to-chess-primary/80 text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24">
          <div className="text-center">
            <h1 className="text-5xl font-bold mb-6">
              Master Your Chess <br />
              <span className="text-chess-secondary">Tournament Preparation</span>
            </h1>
            <p className="text-xl mb-8 max-w-3xl mx-auto text-chess-secondary/90">
              Upload your opponents' games, get AI-powered analysis, and receive personalized 
              training plans with daily drills to dominate your next tournament.
            </p>
            <div className="space-x-4">
              <Link to="/register">
                <Button size="lg" variant="secondary">
                  Start Free Trial
                </Button>
              </Link>
              <Link to="/login">
                <Button size="lg" variant="ghost" className="text-white border-white hover:bg-white/10">
                  Sign In
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-24 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">
              Everything You Need to Win
            </h2>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              Our AI-powered platform analyzes your opponents and creates personalized 
              preparation strategies to give you the competitive edge.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <div key={index} className="bg-white p-8 rounded-lg shadow-md border border-gray-200">
                <div className="h-12 w-12 bg-chess-primary/10 rounded-lg flex items-center justify-center mb-6">
                  <feature.icon className="h-6 w-6 text-chess-primary" />
                </div>
                <h3 className="text-xl font-semibold text-gray-900 mb-3">
                  {feature.title}
                </h3>
                <p className="text-gray-600">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">
            Ready to Elevate Your Game?
          </h2>
          <p className="text-lg text-gray-600 mb-8 max-w-2xl mx-auto">
            Join competitive players and coaches who use our platform to prepare 
            for tournaments and improve their chess performance.
          </p>
          <Link to="/register">
            <Button size="lg">
              Start Your Free Trial
            </Button>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="flex items-center justify-center mb-4">
            <div className="h-8 w-8 bg-chess-primary rounded-lg flex items-center justify-center">
              <span className="text-white font-bold text-lg">♕</span>
            </div>
            <span className="ml-3 text-lg font-semibold">
              AI Chess Tournament Prep Agent
            </span>
          </div>
          <p className="text-gray-400">
            © 2025 Chess Prep Agent. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  )
}
