# API Response Constants
API_SUCCESS = "success"
API_ERROR = "error"

# Chess Engine Constants
DEFAULT_STOCKFISH_DEPTH = 15
DEFAULT_ANALYSIS_TIME = 1.0  # seconds
BLUNDER_THRESHOLD = 300  # centipawns
MISTAKE_THRESHOLD = 100  # centipawns

# Opening Constants
MAX_OPENING_MOVES = 20
COMMON_OPENINGS_TO_TRACK = 10

# Time Control Constants
BULLET_MAX_TIME = 180  # 3 minutes
BLITZ_MAX_TIME = 600   # 10 minutes
RAPID_MAX_TIME = 1800  # 30 minutes

# File Upload Constants
MAX_PGN_FILE_SIZE = 10 * 1024 * 1024  # 10MB
MAX_GAMES_PER_UPLOAD = 1000
ALLOWED_EXTENSIONS = {'.pgn'}

# Email Constants
MAX_EMAIL_LENGTH = 254
MIN_PASSWORD_LENGTH = 8

# Rating Constants
MIN_RATING = 400
MAX_RATING = 3500
DEFAULT_RATING = 1200

# Tournament Prep Constants
MIN_PREP_DAYS = 1
MAX_PREP_DAYS = 90
DEFAULT_PREP_DAYS = 14

# AI Constants
MAX_PROMPT_LENGTH = 4000
MAX_RESPONSE_LENGTH = 2000

# Database Constants
MAX_STRING_LENGTH = 255
MAX_TEXT_LENGTH = 10000

# Cache Constants
CACHE_EXPIRY_HOURS = 24
ANALYSIS_CACHE_KEY_PREFIX = "analysis:"
PREP_PLAN_CACHE_KEY_PREFIX = "prep_plan:"

# HTTP Status Codes (for clarity)
HTTP_200_OK = 200
HTTP_201_CREATED = 201
HTTP_400_BAD_REQUEST = 400
HTTP_401_UNAUTHORIZED = 401
HTTP_404_NOT_FOUND = 404
HTTP_422_UNPROCESSABLE_ENTITY = 422
HTTP_500_INTERNAL_SERVER_ERROR = 500
